pipelines:
  default:
    - step:
        name: Build
        image: php:7.3
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - apt-get install git -y
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --ignore-platform-reqs
          - cp .env codeception.env
          - php -v
        artifacts:
          - '**'
    - parallel:
      # - step:
      #     name: WP Unit Tests ( Latest )
      #     services:
      #       - docker
      #     caches:
      #       - docker
      #     script:
      #       - chmod +x ./bin/setup-pipeline.sh
      #       - ./bin/setup-pipeline.sh
      #       # - ls /usr/local/include/php
      #       # - php -v
      #       # - sleep 20
      #       # - npm run-script test-wpunit
      #       - docker-compose exec -T wordpress  bash -c "cd /var/www/html/wp-content/plugins && ls"
      #       - docker-compose exec -T -w /var/www/html/wp-content/plugins/starcat-review wordpress ./vendor/bin/codecept run wpunit
      - step:
          name: Acceptance Tests ( Latest )
          services:
            - docker
          caches:
            - docker
          script:
            - chmod +x ./bin/setup-pipeline.sh
            - ./bin/setup-pipeline.sh
            # - npm run-script test-build
            - cp -r vendor/pauple/starcat-review-cpt artifacts/addons
            - cp -r vendor/pauple/starcat-review-ct artifacts/addons
            - docker-compose exec -T -w /var/www/html/wp-content/plugins/starcat-review wordpress ./vendor/bin/codecept build
            - docker-compose exec -T -w /var/www/html/wp-content/plugins/starcat-review wordpress ./vendor/bin/codecept run acceptance