pipelines:
  branches:
    develop:
      - step:
          services:
            - docker
          caches:
            - docker
          script:
            - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
            - chmod +x /usr/local/bin/docker-compose
            - docker-compose --file $BITBUCKET_CLONE_DIR/docker-compose.yml run --rm wpbrowser