pipelines:
  default:
    - step:
        name: Build
        image: php:7.3
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --ignore-platform-reqs
          # - cp docker-compose.codeception.env codeception.env
        artifacts:
          - '**'
    - parallel:
      - step:
          name: WP Unit Tests ( Latest )
          services:
            - docker
          caches:
            - docker
          script:
            - ./bin/config/setup-pipeline.sh
            - npm run-script test-wpunit -- --xml test-reports/wpunit.xml
