version: '3.6'
services:
    wordpress:
        build:
            context: ./tests
            args:
              WP_TAG: wordpress:${WP_TAG}
        restart: always
        ports:
            - ${WP_PORT}:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wp
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: pass
            WORDPRESS_DEBUG: 1
            WP_DEBUG_DISPLAY: 0
            WP_DEBUG_LOG: 1
            # WORDPRESS_SKIP_INSTALL: 'yes'
        volumes:
            - ./:/var/www/html/wp-content/plugins/starcat-review
            # - ./artifacts/addons/starcat-review-cpt:/var/www/html/wp-content/plugins/starcat-review-cpt
            - ./artifacts/addons/starcat-review-ct:/var/www/html/wp-content/plugins/starcat-review-ct
            # - ./artifacts/plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./artifacts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: pass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            
