version: "3"

services:
    db:
        container_name: database
        image: mysql:5.7
        ports: # Set up ports exposed for other containers to connect to
            - 3307:3306
        command:
            - "--wait_timeout=28800"
            - "--interactive_timeout=28800"
            - "--max_allowed_packet=16M"

        environment: # Set up mysql database name and password
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: helpie_reviews_acceptance
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        image: wordpress:php7.1-apache
        container_name: wordpress
        depends_on:
            - db
        ports:
            - 80:80
        links:
            - db
        restart: always
        environment:
            WORDPRESS_DB_NAME: helpie_reviews_acceptance
            WORDPRESS_DB_HOST: db:3307
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WP_DEBUG: "true"
            WP_DEBUG_DISPLAY: "false"
            WP_DEBUG_LOG: "true"
        volumes: # Mount relative path source folder on host to absolute path destination folder on docker container
            # - ./dep/themes/astra:/var/www/html/wp-content/themes/astra
            - ./helpie-reviews-build:/var/www/html/wp-content/plugins/helpie-reviews
            # - ./tests/_data/helpie:/var/www/html/wp-content/plugins/helpie
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3307
            PMA_USER: wordpress
            PMA_PASSWORD: wordpress
