version: "3.1"

services:
    wordpress:
        image: wordpress:php7.1-apache
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: scr_test
            WORDPRESS_DEBUG: 1
            WP_DEBUG_DISPLAY: 0
            WP_DEBUG_LOG: 1
        links:
            - db
        volumes: # Mount relative path source folder on host to absolute path destination folder on docker container
            - ./artifacts/dist:/var/www/html/wp-content/plugins/helpie-reviews

    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./tests/_data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        ports: # Set up ports exposed for other containers to connect to
            - "127.0.0.1:3306:3306"
        command:
            - "--wait_timeout=28800"
            - "--interactive_timeout=28800"
            - "--max_allowed_packet=16M"
        environment:
            MYSQL_DATABASE: scr_test
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: wordpress
            PMA_PASSWORD: wordpress
