version: '3.6'
services:
    wordpress:
        build:
            context: ./tests
            args:
              WP_TAG: wordpress:${WP_TAG}
        restart: always
        ports:
            - ${WP_PORT}:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wp
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: pass
            WORDPRESS_SKIP_INSTALL: 1
            WORDPRESS_CONFIG_EXTRA: |
                /* Freemius Dev Mode */
                /* Set Freemius into development mode */
                define( 'WP_FS__DEV_MODE', true );
                define( 'WP_FS__starcat-review_SECRET_KEY', "sk_t=d7~:gkVF1Sw0SJeG!06F[J$dHQ;" );
                /* Skip email activation when a user with the same email already opted-in */
                define( 'WP_FS__SKIP_EMAIL_ACTIVATION', true );
                /* If Freemius was not setup */
                /* define( 'WP_FS__SIMULATE_FREEMIUS_OFF', true ); */
        volumes:
            - ./:/var/www/html/wp-content/plugins/starcat-review
            - ./artifacts/addons/starcat-review-cpt:/var/www/html/wp-content/plugins/starcat-review-cpt
            - ./artifacts/addons/starcat-review-ct:/var/www/html/wp-content/plugins/starcat-review-ct
            - ./artifacts/addons/starcat-review-woo-notify:/var/www/html/wp-content/plugins/starcat-review-woo-notify
            - ./artifacts/addons/starcat-review-photo-reviews:/var/www/html/wp-content/plugins/starcat-review-photo-reviews
            - ./artifacts/plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
            - ./artifacts/plugins/wp-migrate-db:/var/www/html/wp-content/plugins/wp-migrate-db
            - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            # - ./config/wp-config.php:/var/www/html/wp-config.php
            - ./artifacts/uploads:/var/www/html/wp-content/uploads
        depends_on:
            - db
    db:
        image: mysql:5.7
        restart: always
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./artifacts/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        # user: "1000:50"
        environment:
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: pass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            
